Repository trendscenter/coinstac, pull requests merged in 2018-10, with the labels that each got.

#580 Upgrade to Webpack 4
  SETUP.md
  packages/coinstac-ui/package-lock.json
  packages/coinstac-ui/package.json
  packages/coinstac-ui/webpack-dev-server.js
  packages/coinstac-ui/webpack.config.js
Labels: ui

#581 Build script `platform` bug
  packages/coinstac-ui/img/icons/coinstac.png
  packages/coinstac-ui/scripts/build.js
Labels: bug, ui

#582 refactor: move UI artifacts to build directory
  .eslintignore
  .gitignore
  packages/coinstac-ui/.ignore
  packages/coinstac-ui/scripts/build.js
  packages/coinstac-ui/webpack.config.js
Labels: enhancement, ui

#583 Enhancement/fix linting errors
  packages/coinstac-images/.eslintrc.js
  packages/coinstac-ui/app/render/state/ducks/collections.js
  packages/coinstac-ui/app/render/state/graphql/props.js
Labels: enhancement

#590 Move loading spinner to its own file
  packages/coinstac-ui/app/render/components/activity-indicator/activity-indicator.css
  packages/coinstac-ui/app/render/components/activity-indicator/activity-indicator.jsx
  packages/coinstac-ui/app/render/components/app.jsx
  packages/coinstac-ui/app/render/styles/app.scss
Labels: enhancement, ui

#593 Fixed and Tested issue #589
  packages/coinstac-ui/app/render/components/results/displays/result-table.jsx
Labels: bug, ui

#587 Upgrade to React 16.x.x
  .gitignore
  package-lock.json
  packages/coinstac-common/package-lock.json
  packages/coinstac-ui/.ignore
  packages/coinstac-ui/app/render/build/228e7f6ba8cd86353f066d45b22a5c50.png
  packages/coinstac-ui/app/render/build/448c34a56d699c29117adc64c43affeb.woff2
  packages/coinstac-ui/app/render/build/89889688147bd7575d6327160d64e760.svg
  packages/coinstac-ui/app/render/build/bundle.js
  packages/coinstac-ui/app/render/build/e18bbf611f2a2e43afc071aa2f4e1512.ttf
  packages/coinstac-ui/app/render/build/f4769f9bdb7466be65088239c12046d1.eot
  packages/coinstac-ui/app/render/build/fa2772327f55d8198301fdb8bcfc8158.woff
  packages/coinstac-ui/app/render/components/app.jsx
  packages/coinstac-ui/app/render/components/collections/collection-pipeline-input.jsx
  packages/coinstac-ui/app/render/components/collections/collection-pipeline.jsx
  packages/coinstac-ui/app/render/components/computations/computations-list.jsx
  packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx
  packages/coinstac-ui/app/render/components/consortia/consortium-about.jsx
  packages/coinstac-ui/app/render/components/consortia/consortium-pipeline.jsx
  packages/coinstac-ui/app/render/components/consortia/consortium-tabs.jsx
  packages/coinstac-ui/app/render/components/dashboard/dashboard.jsx
  packages/coinstac-ui/app/render/components/pipelines/pipeline-step.jsx
  packages/coinstac-ui/app/render/components/pipelines/pipeline.jsx
  packages/coinstac-ui/app/render/components/pipelines/pipelines-list.jsx
  packages/coinstac-ui/app/render/state/root-reducer.js
  packages/coinstac-ui/package-lock.json
  packages/coinstac-ui/package.json
  packages/coinstac-ui/test/e2e/test.js
  packages/coinstac-ui/webpack.config.js
Labels: enhancement, ui

#594 UI - Get and Display Docker status
  packages/coinstac-docker-manager/src/index.js
  packages/coinstac-ui/app/main/index.js
  packages/coinstac-ui/app/render/components/dashboard/dashboard.jsx
  packages/coinstac-ui/app/render/state/ducks/docker.js
  packages/coinstac-ui/package-lock.json
  packages/coinstac-ui/webpack.config.js
Labels: ui
